### ISSUE TITLE
SNOW-1348217: Don't restrict the Keys being allowed in snowflake.yml

### ISSUE THREAD

**Issue by sfc-gh-cdube** [snowflakedb/snowflake-cli#1017]
### Description

I want to be able to leverage the snowflake.yml file to pass in extra keys, such as app_owner role and namespace destination of the app

### Context

In a CI/CD context, many customers would want to have different owner role for each apps, leveraging the snowflake.yml file for it makes it easy when we use snow streamlit init, since the file is already created. The CD Actions simply parse the snowflake.yml file to find the owner and namespace the app should be deployed to, and adjust the config.toml file used by snow streamlit deploy to pass in role, database and schema.

**Comment by sfc-gh-zblackwood** [comment]
I also heavily use custom keys to avoid having yet another config file required to use snowcli for use-cases like this. I would strongly prefer to have *some* way to have custom config in this file, even if it's in a separate namespace.

**Comment by sfc-gh-turbaszek** [comment]
> I would strongly prefer to have some way to have custom config in this file, even if it's in a separate namespace.

We are working on adding a variables namespace, together with support for templating the values.

**Comment by sfc-gh-turbaszek** [comment]
Not directly but solved by #1065
