### ISSUE TITLE
SNOW-1367016: How can a Snowflake Job be started using the CLI?

### ISSUE THREAD

**Issue by zaramzamzam** [snowflakedb/snowflake-cli#1034]
### SnowCLI version

2.2.0

### Python version

3.11.7

### Platform

macOS-14.4.1-arm64-arm-64bit

### What happened

Previously it was possible to start a Job using 
`snow snowpark jobs create` this was removed in a previous version.

The CLI has the hidden `snow spcs job create ...` command.

Is this the intended way to create a Job?
Is it intended that this is hidden?

### Console output

```Shell
❯ snow spcs job --help

 Usage: snow spcs job [OPTIONS] COMMAND [ARGS]...

 Manages Snowpark jobs.

╭─ Options ────────────────────────────────────────────────────────────────────╮
│ --help  -h        Show this message and exit.                                │
╰──────────────────────────────────────────────────────────────────────────────╯
╭─ Commands ───────────────────────────────────────────────────────────────────╮
│ create   Creates a job to run in a compute pool.                             │
│ logs     Retrieves local logs from a job container.                          │
│ status   Returns the status of a named Snowpark Container Services job.      │
╰──────────────────────────────────────────────────────────────────────────────╯
```
```


### How to reproduce

run `snow spcs job --help`

**Comment by zaramzamzam** [comment]
In order to conform to the tutorials I added a PR #1036 that introduces the `name` parameter and creates the Job using `execute job service ...` .
If `snow spcs job create ...` is the intended way to create jobs this might be helpful.

**Comment by sfc-gh-jsikorski** [comment]
Hi,
thanks for reporting the issue. It is hidden by design- jobs api is going through some changes, and the previous implementation used is deprecated. We will reintroduce it with new syntax in one of the next versions.
