### ISSUE TITLE
SNOW-1452407: Conda package availabitlity

### ISSUE THREAD

**Issue by madten** [snowflakedb/snowflake-cli#1131]
### Description

It seems like this utility is not distributed through [Snowflake conda channel](https://repo.anaconda.com/pkgs/snowflake/). It would be nice to have it there or, if that's not possible ATM, on conda forge.

### Context

This would allow us to keep clean conda env without untracked pip installed packages.

**Comment by sfc-gh-turbaszek** [comment]
@madten do I read correctly that you would like to have snowflake-labs-cli package available on sf conda channel?

**Comment by madten** [comment]
That's correct @sfc-gh-turbaszek.

**Comment by sfc-gh-turbaszek** [comment]
@madten what's the purpose? The package is meant to be a CLI not a package you can use, especially in Snowpark context 🤔

**Comment by sfc-gh-turbaszek** [comment]
Closing as the purpose is not clear and it's not planned.
