### ISSUE TITLE
Return versions from native packages in installPackages

### ISSUE THREAD

**Issue by tvdboom** [snowflakedb/snowflake-cli#116]
Hi,

I am using the InstallPackages function in `/src/snowcli/utils.py` directly in Python (not through cli calls) to create a directory with all dependencies of a certain library (to later upload to a stage and use it in a snowpark udf). Ideally, I would use `perform_anaconda_check=True` and install the anaconda native libraries separately, but I noticed that the function only returns (second argument) the native library's names and not the exact version of those libraries. Getting only the name is not sufficient since I require an exact version to be sure the conda libraries will work properly with the rest of the (non-native) libraries. 

Would it be possible to refactor the function to return the versions together with the libraries, e.g. return `numpy==1.24.0` instead of just `numpy`.

**Comment by sfc-gh-jhollan** [comment]
makes sense - or I wonder if ideally it could return a `dict` that has like "name" and "version" keys.

**Comment by tvdboom** [comment]
That would also do. It does mean that the `parseAnacondaPackages` function in `utils.py` should also check if the exact required version is in the anaconda channel.

**Comment by jamesweakley** [comment]
@tvdboom I opened a PR which partially covers this, but at the moment it doesn't check for the exact version in the anaconda channel. It should be possible to implement, but would require extra HTTP requests since the list of versions isn't in the main channeldata.json response (I think it's just got the latest version).

**Comment by sfc-gh-turbaszek** [comment]
Done in #781
