### ISSUE TITLE
SNOW-1472146: Required to pass `--schema`, can it not default to `public` ?

### ISSUE THREAD

**Issue by kameshsampath** [snowflakedb/snowflake-cli#1182]
### SnowCLI version

Snowflake CLI version: 2.4.0

### Python version

Python 3.11.9

### Platform

macOS-14.5-arm64-arm-64bit

### What happened

When using `snow streamlit` group of commands, some commands asks for `--schema`/fully qualified name and some does not.  When no schema option is provided, I expect the CLI to default to `PUBLIC`.

### Console output

```Shell
With this example streamlit_app in default `PUBLIC` schema of the database,

`snow streamlit describe streamlit_app  --database=my_streamlit_app`

An unexpected exception occurred. Use --debug option to see the traceback. Exception message:

090106 (22000): 01b4ec6b-0002-7f78-0000-006aa2076161: Cannot perform DROP. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.
```

### How to reproduce

1.  `snow sql -q 'CREATE DATABASE my_streamlit_app' `
2.  `snow streamlit deploy --database=my_streamlit_app`
3.  `snow streamlit list` to ensure its created in `PUBLIC` namespace
4.  `snow streamlit describe streamlit_app  --database=my_streamlit_app` - this commands fails the error mentioned above

Try this command,

`snow streamlit get-url streamlit_app --database=my_streamlit_app` it returns without the error.

**Comment by sfc-gh-turbaszek** [comment]
Won't you get the same error when working in worksheet?  I think we do can assume PUBLIC being the default schema but as far as I'm concerned this is not default for all SQL operations (drop being an example here).

**Comment by sfc-gh-turbaszek** [comment]
It's not that CLI expects it, it's a server side implementation. Our goal is to be an interface to this implementation, this suggest we should minimize amount of "custom" logic.

**Comment by sfc-gh-turbaszek** [comment]
Closing then as this is a server-side implementation not necessarily a bug/feature for CLI.
