### ISSUE TITLE
SNOW-1475952: URL Encode Application URLS

### ISSUE THREAD

**Issue by kameshsampath** [snowflakedb/snowflake-cli#1194]
### SnowCLI version

Snowflake CLI version: 2.4.1

### Python version

Python 3.11.9

### Platform

macOS-14.5-arm64-arm-64bit

### What happened

When I try to create an application using  the command `snow app init --name 'My First App' my_first_app` and try to run the same `snow app run` I see the application URL on the output is not URL encoded.

### Console output

```Shell
Creating new application package "My First App_pkg_ksampath" in account.
Checking if stage exists, or creating a new one if none exists.
Performing a diff between the Snowflake stage and your local deploy_root ('/Users/ksampath/mylabs/snowflake/apps/my_first_app/output/deploy') directory.
There are no new files that exist only on the stage.
There are no existing files that have been modified, or their status is unknown.
There are no existing files that are identical to the ones on the stage.
New files only on your local:
README.md
manifest.yml
setup_script.sql
Uploading diff-ed files from your local /Users/ksampath/mylabs/snowflake/apps/my_first_app/output/deploy directory to the Snowflake stage.
Creating new application "My First App_ksampath" in account.
Your application object ("My First App_ksampath") is now available:
https://app.snowflake.com/BIFWCVV/qpb43954/#/apps/application/My First App_ksampath
```

### How to reproduce

1. Create app using the command  `snow app init --name 'My First App' my_first_app`
2. Move to application directory `cd my_first_app`
3.  Run the application `snow run`

You will not the URL of the application resulted out of successful deployment like 

`https://app.snowflake.com/BIFWCVV/qpb43954/#/apps/application/My First App_ksampath` (NOT URL ENCODED)

**Comment by sfc-gh-turbaszek** [comment]
Closed by #1196
