### ISSUE TITLE
Allow creating package zips from Git or HTTP locations through pip

### ISSUE THREAD

**Issue by sfc-gh-hachouraria** [snowflakedb/snowflake-cli#122]
pip accepts a limited range of URL syntax for package names.

For example you could type the following to directly install packages from sources:

```bash
~> pip install 'git+https://github.com/user/repo.git@branch_name'
```

The `snowcli package create [name]` command accepts such URLs as arguments:

```bash
~> snow package create 'git+https://github.com/user/repo.git@branch_name'
```

However, it assumes that the `name` argument is also the filename for `name.zip` and will attempt to create a file named `git+https://github.com/user/repo.git@branch_name.zip`, which is invalid and will result in a final error:

```bash
~> snow package create 'git+https://github.com/user/repo.git@branch_name'
Collecting git+https://github.com/user/repo.git@branch_name
Cloning https://github.com/user/repo.git (to revision branch_name) to /private/var/folders/dj/8bdd294947dbq_y72_whrqj80000gn/T/pip-req-build-lug984pr
  Running command git clone --filter=blob:none --quiet https://github.com/user/repo.git /private/var/folders/dj/8bdd294947dbq_y72_whrqj80000gn/T/pip-req-build-lug984pr
Resolved https://github.com/user/repo.git to commit b76324ac90d93dc3bca382d90841a9ab5f398b50f
[… snipped …]
FileNotFoundError: [Errno 2] No such file or directory: 
'git+https://github.com/user/repo.git@branch_name.zip'
```

This prevents convenient packaging latest or fixed branches of popular repositories when they are required.

Could the `name` in case of URLs please be derived from the downloaded package metadata, or accepted as an optional add-on string?

**Comment by jeffhollan** [comment]
Good point. I like the idea of an optional flag to set package name. Something like `snow package create 'git+...' -n my_package`

**Comment by sfc-gh-turbaszek** [comment]
Done via #947
