### ISSUE TITLE
SNOW-1490800: Error starting Streamlit: No warehouse found for the Streamlit object

### ISSUE THREAD

**Issue by alucryd** [snowflakedb/snowflake-cli#1229]
### SnowCLI version

2.4.1

### Python version

3.8.19

### Platform

Linux-6.9.5-zen1-1-zen-x86_64-with-glibc2.34

### What happened

Deploying a streamlit app does not assign a warehouse to the app despite `query_warehouse` being set in `snowflake.yml`.
![image](https://github.com/snowflakedb/snowflake-cli/assets/1561084/079a8174-5f82-4c3c-b241-54d1e6cd1a40)
I need to manually select a warehouse and reboot the app for it to work.

### Console output

```Shell
N/A
```

### How to reproduce

* Init a streamlit app
* Set your warehouse of choice in `snowflake.yml`
* Deploy and launch the app in Snowflake
* Observe the above error message

**Comment by sfc-gh-pczajka** [comment]
I couldn't replicate the bug - could you provide output of `snow streamlit describe NAME` after the deployment?
Did `snow deploy` command throw any errors or warnings?

**Comment by alucryd** [comment]
Thanks for the quick reply, nothing out of the ordinary during the deploy command, I use GitLab CI with a temporary connection defined as CI variables, it was ported over from a similar pipeline I wrote for snowpark. Running the command locally produces the same result.

```
$ snow streamlit deploy -x --replace
Streamlit successfully deployed and available under https://app.snowflake.com/redacted/redacted/#/streamlit-apps/REDACTED
```

describe shows `query_warehouse` is set to `None`.

**Comment by sfc-gh-pczajka** [comment]
The only way I manage to replicate that result is when I explicitly set `query_warehouse` parameter to `null` in `snowflake.yml`, nothing in the code seem to override this parameter.
Could you run `deploy` command with `--debug` and check what SQL query is executed?

**Comment by sfc-gh-pczajka** [comment]
Closing the issue as we could't replicate the bug
