### ISSUE TITLE
`snow package` doesn't know to ignore streamlit from dependencies

### ISSUE THREAD

**Issue by sfc-gh-jcarroll** [snowflakedb/snowflake-cli#126]
When trying to package a library that only depends on Streamlit for usage in a SiS app, `snow package` doesn't seem to realize that Streamlit is already in the anaconda channel / available in SiS. This effectively breaks the packaging ability since it creates a 2GB zip file that won't run when you upload it to a stage.

Discovered with https://github.com/Valires/streamlit-survey , unsure if it repros on other similar libraries

Repro steps:

```
$ snow package lookup streamlit-survey
"streamlit-survey" not found in Snowflake anaconda channel...
The package is not in Anaconda. Do you want to try to see if it's supported as a custom package (requires pip)? [Y/n]: Y
Collecting streamlit-survey
Downloading streamlit_survey-0.1.0-py2.py3-none-any.whl (12 kB)
Collecting streamlit
# ...
Installing collected packages: pytz, ...
# ...
"pydeck" not found in Snowflake anaconda channel...
"streamlit-survey" not found in Snowflake anaconda channel...
"GitPython" not found in Snowflake anaconda channel...
-----> "streamlit" not found in Snowflake anaconda channel... <---------
# ...
```

**Comment by sfc-gh-jcarroll** [comment]
I don't understand the behavior since when I look at https://repo.anaconda.com/pkgs/snowflake/ I can see Streamlit listed in the channel. Not sure if it has some special handling or limitation that causes it to be excluded

But regardless we're regularly telling SiS customers to side-load packages with `snow package`. And it would be very unusual to try to load a package for a regular non-SiS snowpark function that depended on Streamlit. So it may be worth a custom exclusion to prevent this behavior in that case (could be behind a flag etc if needed).

**Comment by sfc-gh-turbaszek** [comment]
@sfc-gh-jcarroll is this still an issue?

**Comment by sfc-gh-jcarroll** [comment]
I haven't used snowcli in a while or kept up with the latest updates. Trying to repro this now I get a different error. But it's possible I'm doing something incorrectly.

```
% snow --version
SnowCLI Version: 2.0.0

% pip install streamlit-survey
Collecting streamlit-survey
  Downloading streamlit_survey-0.1.0-py2.py3-none-any.whl (12 kB)
...
Installing collected packages: streamlit-survey
Successfully installed streamlit-survey-0.1.0

% snow snowpark package lookup streamlit-survey -y --debug
2024-02-13 10:08:58 INFO [snowflake.cli.plugins.snowpark.package_utils] 'streamlit-survey' not found in Snowflake anaconda channel...
2024-02-13 10:08:58 INFO [snowflake.cli.plugins.snowpark.package_utils] pip failed with return code -6.
            If pip is installed correctly, this may mean you`re trying to install a package
            that isn't compatible with the host architecture -
            and generally means it has native libraries.
Lookup for package streamlit-survey resulted in some error. Please check the package name or try again with -y option
```

I briefly looked at pip return code -6 but wasn't able to find any info on that error.

**Comment by sfc-gh-turbaszek** [comment]
I'm closing the issue because I validated on current main and seems to be working fine:
```
Package streamlit_survey.zip created. You can now upload it to a stage using
snow snowpark package upload -f streamlit_survey.zip -s <stage-name>`
and reference it in your procedure or function.
Remember to add it to imports in the procedure or function definition.

The package streamlit-survey is successfully created, but depends on the following
Anaconda libraries. They need to be included in project requirements,
as their are not included in .zip.
streamlit
jinja2
...
```
