### ISSUE TITLE
SNOW-1526664: unable to log in to container registry with a protected private key

### ISSUE THREAD

**Issue by sfc-gh-cwachiuri** [snowflakedb/snowflake-cli#1297]
### SnowCLI version

2.5.0

### Python version
3.11

### Platform

Windows

### What happened

 There are issues logging in to Snowcli using an encrypted private key on Windows OS.
They have set environment and user variables with the name PRIVATE_KEY_PASSPHRASE , but  snowcli is still raising an error that the passphrase needs to be set under the PRIVATE_KEY_PASSPHRASE environment variable  . 
### Console output

```Shell
thepassphrase needs to be set under the PRIVATE_KEY_PASSPHRASE environment variable
```

#### set the default snowflake connection based on the config.toml file
snow --config-file config.toml connection set-default "snowconn"

#### login to the snowflake image registry
snow --config-file config.toml spcs image-registry login

### The config.toml file 
default_connection_name = "snowconn"
[connections.snowconn]
account = ""
user = ""
authenticator = "SNOWFLAKE_JWT"
private_key_path = ""
role = "CONTAINER_USER_ROLE"

**Comment by sfc-gh-pczajka** [comment]
Hi @sfc-gh-cwachiuri !

I repeated the settings and they seem to work:
```
(venv) PS C:\Users\pczajka> $Env:PRIVATE_KEY_PASSPHRASE = '***'
(venv) PS C:\Users\pczajka> snow --config-file .\Snowflake\config.toml connection test
+--------------------------------------------------+
| key             | value                          |
|-----------------+--------------------------------|
| Connection name | None                           |
| Status          | OK                             |
| Host            | ***                            |
| Account         | ***                            |
| User            | pczajka                        |
| Role            | ACCOUNTADMIN                   |
| Database        | not set                        |
| Warehouse       | not set                        |
+--------------------------------------------------+
```
config.toml:
```
[connections]
[connections.default]
account = "***"
user = "pczajka"
host = "***"
authenticator = "SNOWFLAKE_JWT"
role = "accountadmin"
private_key_path = "***"
```

How did you set the environment variable? I noticed that variables set via `XSET` and control panel are not visible in PowerShell

**Comment by sfc-gh-pczajka** [comment]
I'm closing the issue as we're unable to replicate the bug
