### ISSUE TITLE
SNOW-1540572: When running an app from a given --project path, the post_deploy scripts must be found relative to that path

### ISSUE THREAD

**Issue by etorreborre** [snowflakedb/snowflake-cli#1325]
### SnowCLI version

2.6.1

### Python version

3.11.18

### Platform

macOS-14.2.1-arm64-arm-64bit

### What happened

I am running a `snowflake.yaml` file to start an app, with the `--project` option:
```
> snow app run --project my_path
```

That file specifies a script to run as `post_deploy` but the script is not found, unless I give a full path, starting from the point where I'm invoking the `snow` command.

### Console output

```Shell
The error is 

Executing application post-deploy actions
  Executing SQL script: scripts/post_deploy.sql

An unexpected exception occurred. Use --debug option to see the traceback. Exception message:

[Errno 2] No such file or directory: 'scripts/post_deploy.sql'
```
```


### How to reproduce

This can be reproduced by takin [this test example](https://github.com/snowflakedb/snowflake-cli/tree/8f638f4938ddb2957c011effdbeef173482051c4/tests_integration/test_data/projects/napp_application_post_deploy) and nesting it into a `root` directory.

Then from the `root` directory run:
```
snow app run --project napp_application_post_deploy
```

**Comment by etorreborre** [comment]
Hi @sfc-gh-melnacouzi, thanks for fixing this issue! 
Do you have an idea of when a new release will incorporate the fix?

**Comment by sfc-gh-melnacouzi** [comment]
> Hi @sfc-gh-melnacouzi, thanks for fixing this issue! Do you have an idea of when a new release will incorporate the fix?

@etorreborre we should have a new release within 2 weeks.
