### ISSUE TITLE
SNOW-1569814:  Support for Organizing Streamlit Apps in Subdirectories

### ISSUE THREAD

**Issue by sfc-gh-jdemlow** [snowflakedb/snowflake-cli#1408]
### Description

I'm working on a Streamlit application and want to keep the repository organized by placing the app and its associated files in an app/ directory rather than the root. While everything functions correctly when placed in the root, I'm struggling to make it work from a subdirectory. The main challenge seems to be with specifying the paths in the snowflake.yml file and ensuring that additional source files are correctly referenced and uploaded to the Snowflake stage.

For instance, I've tried setting main_file: app/streamlit_app.py and adding source files like app/utils.py to the additional_source_files section. However, this setup results in errors related to the file paths, particularly when using relative paths that attempt to navigate outside the intended structure.

For internal teams https://snowflake.slack.com/archives/C03E8TLQ7LP/p1719331501385529 

I was asked to put in a feature request about a month ago please feel free to reach out to me

### Context

I feel like this is just something that would be very nice to have in a streamlit development approach

**Comment by sfc-gh-turbaszek** [comment]
Upcoming Snowflake CLI 3.0 is going to support multiple Streamlits apps in a single project. You will be able to specify what files are necessary for each app. Having said that we will have to wait for next release.

**Comment by sfc-gh-turbaszek** [comment]
Done in #1394
