### ISSUE TITLE
SNOW-1644654: "snow git execute" does not work if the branch name contains "/"

### ISSUE THREAD

**Issue by sfc-gh-pczajka** [snowflakedb/snowflake-cli#1512]
Hello,

I'm new to snowflake and command-line, so sorry if this is simple thing. I'm trying to execute the below command - 

`snow git execute @my_REPO/branches/\"feature/DAT-9988-set-up-snowflake-process\"/schema/scripts/deploy.sql --variable SNOWFLAKE_DATABASE_NAME=$SNOWFLAKE_DATABASE_NAME --variable SNOWFLAKE_SCHEMA_NAME=$SNOWFLAKE_SCHEMA_NAME --variable SNOWFLAKE_STAGING_SCHEMA_NAME=$SNOWFLAKE_STAGING_SCHEMA_NAME`

And it is failing with the below error- 

093505 (42601): 01b5c118-060b-1edf-0000-247125b3513e: Files paths in git repositories must specify a scope. For example, a branch name, a tag name, or a valid commit hash. Commit hashes are between 6 and 40 characters long.

When I see the debug logs or query history I see that it is trying to execute 
`ls '@my_REPO/branches/"feature/'`

This is not the correct path. The branch name is 

"feature/DAT-9988-set-up-snowflake-process" (with quotes). And I'm not able to escape characters due to some reason. If it helps I'm able to run this successfully - 

`snow git list-files @my_REPO/branches/\"feature/DAT-9988-set-up-snowflake-process\"/schema/scripts/deploy.sql --debug`

And for this I see in the logs - 

`ls '@my_REPO/branches/"feature/DAT-9988-set-up-snowflake-process"/schema/scripts/deploy.sql'`

Also this works - 

`snow sql -q "EXECUTE IMMEDIATE FROM @my_REPO/branches/\"feature/DAT-9988-set-up-snowflake-process\"/schema/scripts/deploy.sql  USING (SNOWFLAKE_DATABASE_NAME => ${SNOWFLAKE_DATABASE_NAME}, SNOWFLAKE_SCHEMA_NAME => ${SNOWFLAKE_SCHEMA_NAME}, SNOWFLAKE_STAGING_SCHEMA_NAME => ${SNOWFLAKE_STAGING_SCHEMA_NAME})"`

Can anyone advise what can I do to fix it? Many thanks in advance.

_Originally posted by @himanshumunjal in https://github.com/snowflakedb/snowflake-cli/discussions/1338_

**Comment by sfc-gh-astus** [comment]
Fixed, will be released in 3.0.0.
