### ISSUE TITLE
SNOW-1650685: snow snowpark package create generates empty .zip archive

### ISSUE THREAD

**Issue by patawan** [snowflakedb/snowflake-cli#1535]
### SnowCLI version

2.8.0

### Python version

3.11.5

### Platform

Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

### What happened

While attempting to generate a `.zip` archive to upload to snowflake for use in a Python worksheet, the command `snow snowpark package create CausalPy` generates a `.zip` archive that contains no files.

### Console output

```Shell
Package CausalPy.zip created. You can now upload it to a stage using
snow snowpark package upload -f CausalPy.zip -s <stage-name>
and reference it in your procedure or function.
Remember to add it to imports in the procedure or function definition.
```

### How to reproduce

execute the command
`snow snowpark package create CausalPy`.

I have also tried passing multiple flags to the command and they all yield the same result:[
- `snow snowpark package create CausalPy --ignore-anaconda`
- `snow snowpark package create CausalPy --ignore anaconda --allow-shared-libraries`
- `snow snowpark package create CausalPy --ignore anaconda --allow-shared-libraries --index-url https://pypi.python.org/simple`

**Comment by sfc-gh-jsikorski** [comment]
Issue was fixed in https://github.com/snowflakedb/snowflake-cli/releases/tag/v2.8.1
