### ISSUE TITLE
SNOW-1658414: Add deterministic behaviour to create the correct connection string to connections.toml

### ISSUE THREAD

**Issue by sfc-gh-nobrien** [snowflakedb/snowflake-cli#1547]
### Description

Problem:
When a new connection is added to the config file, it always uses the format for CONFIG.TOML

[connection.name]

When a connections.toml file exists in the same directory, as per documentation, the connection is written to that file instead using the same format as above. However, as also noted in the documentation, connections.toml uses a different format of 

[name]

The new connection cannot be found unless the toml file is modified after snowcli writes the connection to conenction.toml

Requirement:
As we know the connections.toml uses a different format, and snowcli already knows to write to that rather than conifg.toml if it exists, it should also write the connection in the correct format.

### Context

A new connection that is written to a connections.toml file cannot be found, giving a error:
```
 Connection connections.tester2 is not configured
```
So when used, the file needs to be edited after the connection has been added.

**Comment by sfc-gh-tmathew** [comment]
Linking to #1591 for similar issues with connection.toml
