### ISSUE TITLE
SNOW-1661024: Add generate-jwt command

### ISSUE THREAD

**Issue by sfc-gh-vtimofeenko** [snowflakedb/snowflake-cli#1566]
### Description

Snowsql allows generating JWT using `--generate-jwt` flag ([doc](https://community.snowflake.com/s/article/How-To-Use-SnowSQL-to-generate-JWT-Token-for-Key-Pair-Authentication-Mechanism)). Would be great to have this in `snowcli`.

### Context

1. General snowsql parity
2. Generating JWT for [REST API](https://docs.snowflake.com/en/developer-guide/snowflake-rest-api/authentication)
3. SPCS released [programmatic access to endpoints](https://docs.snowflake.com/en/developer-guide/snowpark-container-services/working-with-services#public-endpoint-access-from-outside-snowflake-and-authentication).
    The flow is:
    1. Generate JWT
    2. Exchange JWT for access token
    5. Use access token to access SPCS endpoint
4. Generating JWT for [SQL API](https://docs.snowflake.com/en/developer-guide/sql-api/authenticating#using-key-pair-authentication) -- maybe less useful in CLI context, but useful for debugging/development purposes

**Comment by sfc-gh-turbaszek** [comment]
Added in #1712
