### ISSUE TITLE
SNOW-1670821: connections command reads and writes to different config files

### ISSUE THREAD

**Issue by sfc-gh-tmathew** [snowflakedb/snowflake-cli#1591]
### SnowCLI version

2.8.1

### Python version

3.10.9

### Platform

macOS-14.6.1-arm64-arm-64bit

### What happened

I was attempting to add a new connection using snowcli command options

I ran `snow connection add` answered the prompts to add "myconnection" and got notified that the connection was added to `/Users/<myusername>/.snowflake/config.toml` 

But when I run `snow connection list` I was not seeing the connection "myconnection" I added successfully in the previous step show in the output. I verified that the connection entry exists in config.toml.

It seems the `snow connection list` was reading from a connections.toml file that I had setup for Visual Studio Code based on Snowflake Docs to align with the python connector configuration setting. 

### How to reproduce

- create a `connections.toml` file in the `~/.snowflake` directory
- use `snow connection add` command to add a new connection
- output of `snow connection list` will not show the recently added connection.

**Comment by kharigardner** [comment]
+1 , i think there is a mismatch between the cli reading and writing config. when it reads, it will read the `connection.toml` config from the VSCode extension for example first, but when doing a `snow connection add` command, it will write to a `config.toml` and ignore it
