### ISSUE TITLE
SNOW-1703629: Snowpark packaging does not actually ever log pip install error messages

### ISSUE THREAD

**Issue by jamesweakley** [snowflakedb/snowflake-cli#1639]
### SnowCLI version

3.0.0rc2

### Python version

3.10

### Platform

Linux-6.8.0-45-generic-x86_64-with-glibc2.36

### What happened

When building a snowpark package, any pip failures get reported as "returned non-zero exit status 1".

This is because although `pip_wheel` [attempts to catch](https://github.com/snowflakedb/snowflake-cli/blob/372ced75215a53ffc51bc5f0af83cb4fa105478c/src/snowflake/cli/_plugins/snowpark/package_utils.py#L236) `subprocess.CalledProcessError`, that exception is never thrown unless you pass `check=True` to `subprocess.run`.

I tested this by editing the source locally and adding  `check=True`, immediately I started getting back meaningful error messages.

**Comment by sfc-gh-turbaszek** [comment]
Fixed in #1701
