### ISSUE TITLE
SNOW-1782025: config.toml file requires a default connection

### ISSUE THREAD

**Issue by davidrichardsonleit** [snowflakedb/snowflake-cli#1829]
### SnowCLI version

3.1.0

### Python version

3.11.6

### Platform

macOS-14.7-x86_64-i386-64bit

### expected behaviour
when passing connection parameters to the snow cli you do not require connection details in the config.toml file.

### actual behaviour
if you provide connection parameters to the snow cli then if you do not have a default connection in the config.toml file the following exception is raised:

```
 Error
│ Connection default is not configured  
```

### Console output

```Shell
Error 
│ Connection default is not configured
```

### How to reproduce

1. remove default connection from config.toml
2. execute:
``` bash
snow sql --filename ./do_somethiung.sql \
      --account $ACCOUNT \
      --user $USER \
      --private-key-path $PRIVATE_KEY_PATH \
      --role $ROLE \
      --warehouse $WAREHOUSE \
      --authenticator SNOWFLAKE_JWT
```

**Comment by sfc-gh-jsikorski** [comment]
Hi David,
could you paste contents of your `config.toml` file, with all the sensitive data hidden?
My first guess would be, that you have a line that says `default_connection_name = "default"`, but there is no section like `[connections.default]`.
If you want to provide all connections details from command line, please use `--temporary-connection` option.

**Comment by sfc-gh-turbaszek** [comment]
Closing due to no response and the fact that probably `--temporary-connection` is the solution:
https://docs.snowflake.com/developer-guide/snowflake-cli/connecting/configure-connections#use-a-temporary-connection
