### ISSUE TITLE
SNOW-1837161: Bumping `snowflake` dependency version

### ISSUE THREAD

**Issue by kameshsampath** [snowflakedb/snowflake-cli#1906]
### Description

As a developer I might have situations/need where I might have CLI installed as package along side `snowflake`. Where I will use `snow` for all my CLI needs and `snowflake` API for managing  stuff programatically. 

Currently Snowflake CLI has version constraint for `snowflake==0.12.0` , which is not allowing me to install the latest version  `>=1.0.2` of the `snowflake` package, putting constraints on using create or alter and similar new functionalities inside the my app along side `snow` 

### Context

When I need to do something like this my Python env

`requirements.txt`

```
snowflake-snowpark-python
snowflake-cli
snowflake
```

**Comment by sfc-gh-astus** [comment]
Bumped `snowflake.core` to 1.0.2 #1908 . Change will be released in January release.
