### ISSUE TITLE
SNOW-956680: Add python connector diagnostic so we can also use snow cli to test customer connectivity issues

### ISSUE THREAD

**Issue by sfc-gh-cconner** [snowflakedb/snowflake-cli#520]
### Description

Add these flags for the python connector:

enable_connection_diag
connection_diag_log_path
connection_diag_whitelist_path

This will allow us to test connectivity issues using the python connector's diagnostic report.

@sfc-gh-cconner will implement.

**Comment by sfc-gh-cconner** [comment]
PR:

https://github.com/Snowflake-Labs/snowcli/pull/669

**Comment by sfc-gh-turbaszek** [comment]
Done via #669
