### ISSUE TITLE
Can't create function with parameter defined with optional parameters

### ISSUE THREAD

**Issue by sfc-gh-jhansen** [snowflakedb/snowflake-cli#53]
I'm trying to create a Python UDF which takes a `NUMBER(35,4)` parameter (and returns a `NUMBER(35,4)` parameter). Here is what the default section of my app.toml looks like:

```
[default]
input_parameters = "(temp_f number(35,4))"
return_type = "number(35,4)"
name = "fahrenheit_to_celsius_udf"
handler = "app.main"
file = "app.zip"
```

When I try and create/update the function, snowcli runs the following query: `describe function fahrenheit_to_celsius_udf(number(35,4);` which results in the following error:

001003 (42000): SQL compilation error:
syntax error line 1 at position 56 unexpected ';'.

It looks like the issue is in `snow_connector.py:generate_signature_from_params()`. That function doesn't seem to correctly handle parameters with optional parameters.

**Comment by sfc-gh-jhollan** [comment]
Thanks much @thomaseibner ! Just pushed out release with this fix. Let me know if this is resolved and can close issue

**Comment by sfc-gh-turbaszek** [comment]
Done in #634
