### ISSUE TITLE
SNOW-1006186: snow object stage copy should return files in folders, not flatten out directory structure

### ISSUE THREAD

**Issue by sfc-gh-zblackwood** [snowflakedb/snowflake-cli#643]
### SnowCLI version

SnowCLI Version: 2.0.0-alpha.1

### Python version

3.8.15

### Platform

macOS-14.2.1-arm64-arm-64bit

### What happened

I downloaded the files from a stage, but rather than showing up in the same structure as the stage (nested into folders), all the files were dumped into the current directory, rather than into folders.

I tested this with snowcli 1.1 and with 2.0.0-alpha.1

### How to reproduce

Try to copy from a stage that has files in folders to the local directory.

```sh
snow object stage copy <STAGE_NAME> .
```

**Comment by sfc-gh-astus** [comment]
We are blocked by python connector
