### ISSUE TITLE
SNOW-1053803: Second-chance Anaconda run suffers from version lag relative to PyPi

### ISSUE THREAD

**Issue by jamesweakley** [snowflakedb/snowflake-cli#763]
### Description

Currently [in snowpark_shared.py](https://github.com/Snowflake-Labs/snowcli/blob/main/src/snowflake/cli/plugins/snowpark/snowpark_shared.py#L76), we do a second `pip install` of the `requirements.other.txt` file and look for packages included as dependencies that can be satisfied by Anaconda.

This approach works well in general, but something I'm running into more frequently is that the `pip install` pulls the latest version of the package from PyPi, and it then fails the [Anaconda version check](https://github.com/Snowflake-Labs/snowcli/blob/main/src/snowflake/cli/plugins/snowpark/package_utils.py#L315) because Anaconda typically lags behind PyPi.

As an experiment, I've monkey-patched snowpark_shared.py [here](https://github.com/Snowflake-Labs/snowcli/blob/main/src/snowflake/cli/plugins/snowpark/snowpark_shared.py#L65) so that when `requirements.other.txt` is written out, we include both the "other" requirements and the "snowflake" requirements. This means that in my original `requirements.txt` I can pin specific versions of packages that I know will be pulled in as dependencies, and I pin them to the latest version that's available on Anaconda. This means that they satisfy the Anaconda version check, are added to the "snowflake" requirements and its files are deleted.

I'll leave this in place for a while, and eventually open a PR if it proves to be a good solution.

Meanwhile I'll happily take suggestions on alternate ways to solve this.

### Context

So that the size of app.zip files are much smaller and don't include native code.

**Comment by sfc-gh-jsikorski** [comment]
Hi, thanks for noticing the problem. Could you give me some example package names, to recreate the problem?

**Comment by jamesweakley** [comment]
If you include `july` (PyPi only), it'll bring in `matplotlib` in the second pass, but a newer version than what's on Anaconda.

This will mean that matplotlib is downloaded and bundled in app.zip.

With my workaround, I can put `matplotlib==3.7.4` in requirements.txt which will keep it pinned during the second round.
