### ISSUE TITLE
SNOW-1055429: Only pin dependencies to versions available on Anaconda

### ISSUE THREAD

**Issue by jamesweakley** [snowflakedb/snowflake-cli#770]
### Description

It would make life easier if we could use the same conda environment for snowcli and proc/function development. But in order for the local code to run with the same environment as it will in Snowflake, we have to pin versions to the latest Anaconda version which conflicts with snowcli.

### Context

For most people this would be a convenience so that they didn't have to juggle development and deployment virtual environments.
For me, I actually have snowcli as a dependency in our devkit library, which also depends on a package we run in Snowflake (which has Anaconda versions pinned). This creates some dependency hell for me locally.

**Comment by sfc-gh-turbaszek** [comment]
It sounds like more as a best practice to promote than a feature request. Our near term goal is to release the CLI as a binary that do not cause any conflicts with local development environment.
