### ISSUE TITLE
SNOW-1064130: Snow CLI fails when multiple connections with the same name are in the config.toml file

### ISSUE THREAD

**Issue by sfc-gh-kogunkoya** [snowflakedb/snowflake-cli#813]
### SnowCLI version

2.0.0

### Python version

3.11.7

### Platform

MAC OS

### What happened

Creating a config.toml file that has the multiuple connections with the same name fails with the error:

`An unknown error happened while loading '/Users/user/Library/Application Support/snowflake/config.toml'
`

### Console output

```Shell
An unknown error happened while loading '/Users/user/Library/Application Support/snowflake/config.toml'
```

### How to reproduce

[connections]
[connections.test]
account = "testacc"
user = "testuser"
password = "test"
role = "role"

[connections.test]
account = "account"
user = "user"
password = "password"
role = "accountadmin"

**Comment by sfc-gh-pczajka** [comment]
The fix will be included in 2.5.0 release (expected: 19.06)
