### ISSUE TITLE
SNOW-1137351: deploy snow cli python vectorized UDF 

### ISSUE THREAD

**Issue by peddadap** [snowflakedb/snowflake-cli#827]
### Description

Does the CLI support creating python vectorized UDF's ? 

For example https://docs.snowflake.com/en/developer-guide/udf/python/udf-python-batch

If one would like to use snow-cli constructs to create a Python vectorized UDF, is that something that snow-cli currently supports?

### Context

We use snowcli to do our ci/cd deployments for code written in python, the command line snow snowpark options help us deploy object remotely 

It would be nice to support full range of objects

**Comment by sfc-gh-pjob** [comment]
It's possible that we don't need to do anything special to make it working and decorating your python code as described in the docs linked by you will be enough.

We'll prepare a test case confirming work of vectorized UDFs but we will need some time to take care of it. However I encourage to try to just use it and share your observations if you find any troubles.

Of course all above is about SnowCLI v2.0.0 +.

**Comment by peddadap** [comment]
Thank you for the response, tested out the vectorized UDF using  SnowCLI v2.0.0. +  Of the two variants 

Python Vectorized UDF's : https://docs.snowflake.com/en/developer-guide/udf/python/udf-python-batch 

The snow cli "snowflake.yml" bindings on method inputs and outputs were primitives and worked out okay. 

**The second variant  : UDFT's return type in a table, i.e. data-frame itself**

https://docs.snowflake.com/en/developer-guide/udf/python/udf-python-tabular-vectorized

From a 'yml' specification for snow-cli  deployment of UDFT's what would be the equivalent for a return Type when its a pandas dataframe? 

>> for example in the yaml here what would be the return value if I were sending the name dataframe back ?

definition_version: 1
snowpark:
  project_name: player_health
  stage_name: python
  src: '/python/udf'
  functions:
  - name: vctr_add_inputs
    handler: vectorized_sample.vctr_add_inputs
   # all inputs are automatically being converted into pandas series and a final pandas dataframe is passed to method
    signature:
    - type: integer
      name: x
    - type: float
      name: y
    returns: ??  # what would be the equivalent type for returning a table , **can return have a map structure ?**


The link here gives possible hints on what the python to sql equivalent is likely to be, however I'm not clear on what exactly the return type would be in the 'yml' for UDTF

 https://docs.snowflake.com/en/developer-guide/udf/python/udf-python-batch#type-support


>> SQL CREATE STATEMENT -- need equivalent 'yml' for snow-cli deployment  on the return value 

create or replace function summary_stats(id varchar, col1 float, col2 float, col3 float, col4 float, col5 float)
returns table (column_name varchar, count int, mean float, std float, min float, q1 float, median float, q3 float, max float)
language python
runtime_version=3.8
packages=('pandas')
handler='handler'
as $$
from _snowflake import vectorized
import pandas

class handler:
    @vectorized(input=pandas.DataFrame)
    def end_partition(self, df):
      # using describe function to get the summary statistics
      result = df.describe().transpose()
      # add a column at the beginning for column ids
      result.insert(loc=0, column='column_name', value=['col1', 'col2', 'col3', 'col4', 'col5'])
      return result
$$;

**Comment by sfc-gh-turbaszek** [comment]
I think this will work:
`returns: "table(column_name varchar, count int, mean float, std float, min float, q1 float, median float, q3 float, max float)"`

**Comment by peddadap** [comment]
Seeing an error around the lines  on the out of box example 

## A slight variation in implementation, instead of the class example from snowflake in UDTF's I have used a simple method to test out the snowcli deployment , the error is below

ProgrammingError: 100357 (P0000): 01b2b3a6-0d05-bb06-0002-70ee0b6af4ae:
Vectorized input to Python table functions is not supported in function
VCTR_SUMMARY_STATS with handler vector_operations.vctr_summary_stats

Python Code : 

import pandas as pd

''' vectorized implementation '''

def vctr_add_inputs(df)->float:
  
   return df[0] + df[1]

def vctr_summary_stats(df):
      # using describe function to get the summary statistics
      result = df.describe().transpose()
      # add a column at the beginning for column ids
      result.insert(loc=0, column='column_name', value=['col1', 'col2', 'col3', 'col4', 'col5'])
      return result

# For local debugging. Be aware you may need to type-convert arguments if
# you add input parameters
if __name__ == "__main__":
  ...
 
vctr_add_inputs._sf_vectorized_input = pd.DataFrame

vctr_summary_stats._sf_vectorized_input = pd.DataFrame
  
yml file >> 

definition_version: 1
snowpark:
  project_name: sample_project
  stage_name: python
  src: /tmp/examples
  functions:
  - name: vctr_add_inputs
    handler: vector_operations.vctr_add_inputs
    signature:
    - type: integer
      name: x
    - type: float
      name: y
    returns: float
  - name: vctr_summary_stats
    handler: vector_operations.vctr_summary_stats
    signature:
    - type: string
      name: id
    - type: float
      name: co1
    - type: float
      name: col2
    - type: float
      name: co3
    - type: float
      name: col4
    - type: float
      name: col5
    returns: table (column_name varchar, count int, mean float, std float, min float, q1 float, median float, q3 float, max float)

**Comment by sfc-gh-turbaszek** [comment]
Closing due to no response and no explicit bug. Please feel free to reopen if you see something is missing
