### ISSUE TITLE
SNOW-1261540: SPCS Documentation contains incompatible compute pool name

### ISSUE THREAD

**Issue by sfc-gh-smason** [snowflakedb/snowflake-cli#927]
### SnowCLI version

2.1.1

### Python version

3.12.2

### What happened

In the SnowCLI SPCS [documentation](go/spcs-bug-dashboard) page where the docs describe how to create a pool.  The name "pool-1" is used, "-" is not allowed as a name for a pool.

The following error is provided when using the example:

> 'pool-1' is not a valid compute pool name. Note that compute pool names must be unquoted identifiers.

Suggestion is to remove the "-" and replace with underscore.  In the command reference, this same example is used.

**Comment by sfc-gh-mheavin** [comment]
This issue is being fixed in a separate documentation JIRA.

**Comment by sfc-gh-pjob** [comment]
@sfc-gh-mheavin please close this GitHub ticket after deploying changes in docs.
