### ISSUE TITLE
SNOW-1261748: Auto-Complete for MacOS

### ISSUE THREAD

**Issue by sfc-gh-smason** [snowflakedb/snowflake-cli#928]
### Description

Currently, (SnowCLI v2.1.1) does not support auto-complete. A feature that is available in most CLI environments to increase developer productivity.

**Comment by sfc-gh-ccoleman** [comment]
I would really love to see this feature. It really speeds up and reduces the barrier to entry for developers first using the tool.

**Comment by sfc-gh-turbaszek** [comment]
Done in #1109
