### ISSUE TITLE
SNOW-1272319: Alias SnowCLI SPCS List and Delete Commands in SPCS create tree

### ISSUE THREAD

**Issue by sfc-gh-smason** [snowflakedb/snowflake-cli#938]
### Description

SPCS GAs at Summit. The request is to alias list/drop commands in `snow spcs...` command tree. So that the user can issue a command like `snow spcs create compute-pool` and then to verify their creation, they only need to up-arrow and replace `create` with `list` (e.g. `snow spcs list compute-pool`). The transition to the snow object command tree uses a different syntax than the create CLI tree.  Create uses verb/noun and object uses noun/verb.

For example:
`snow spcs compute-pool create`
`snow object list compute-pool`

**Comment by sfc-gh-smason** [comment]
In JIRA this should be [SNOW-1269556](https://snowflakecomputing.atlassian.net/browse/SNOW-1269556)

**Comment by sfc-gh-anugupta** [comment]
Thanks for the feedback . We are looking into how we can update the cmd design for it and will update on it

**Comment by sfc-gh-pczajka** [comment]
Hi!
These aliases will be included in 2.4.0 release
