### ISSUE TITLE
SNOW-1282073: Interactive SQL mode for snowflake-cli

### ISSUE THREAD

**Issue by sfc-gh-vtimofeenko** [snowflakedb/snowflake-cli#946]
### Description

Since `snow sql` allows running one-off statements from the terminal, I only open `snowsql` when I want to have an interactive session. Would be great if `snow sql` provided an interactive experience like `snowsql` does.

### Context

Parity with `snowsql`

cc: @sfc-gh-anugupta

**Comment by sfc-gh-vtimofeenko** [comment]
Personal wishlist of `snowsql` interactive mode specific options

* `vi` mode keybindings
* `output_format=[psql|fancy_grid|orgtbl|expanded]`
* Ability to switch `output_format` live using `!set` command

**Comment by sfc-gh-turbaszek** [comment]
Closing in favor of duplicate in #1586
