### ISSUE TITLE
SNOW-1335887: Ability to use CLI to produce short-lived credentials for applications that don't support browser-based SSO

### ISSUE THREAD

**Issue by dijitali** [snowflakedb/snowflake-cli#994]
### Description

It would be great if the CLI could be used to produce a short-lived, reusable credential for another application to authenticate with.

### Context

Specifically I'm working on projects using [R](https://www.r-project.org/) and the ODBC driver.  Although the ODBC driver supports the [`externalbrowser` option](https://docs.snowflake.com/en/user-guide/admin-security-fed-auth-use#setting-up-browser-based-sso) for the `authenticator` parameter, when working on a containerised project locally, the container is unable to launch a browser on the host machine.  

If the Snowflake CLI on my local machine could pass credentials to the container when it launches (via a volume mount, for instance), it would be very helpful.

**Comment by sfc-gh-turbaszek** [comment]
@dijitali can you describe what credentials information you need?

**Comment by sfc-gh-turbaszek** [comment]
@dijitali please feel free to reopen with more details. Closing for now due to inactivity.
